name = "thor-commerce"
compatibility_date = "2025-04-14"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "thor-db"
database_id = "2da233e7-1801-4da4-8164-83b09d679ab6"

[[kv_namespaces]]
binding = "KV"
id = "410fc2e5baa049b2a8ce18d72b9a3734"

[[r2_buckets]]
binding = "R2"
bucket_name = "thor-js"

[[durable_objects.bindings]]
name = "CART_DO"
class_name = "CartDurableObject"
script_name = "thor-commerce-do"

[[durable_objects.bindings]]
name = "INVENTORY_DO"
class_name = "InventoryDurableObject"
script_name = "thor-commerce-do"

[[queues.producers]]
binding = "ORDER_QUEUE"
queue = "thor-order-events"

[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "thor-email-queue"

[ai]
binding = "AI"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "thor_events"
