name = "thor-commerce"
compatibility_date = "2025-04-14"
main = "./worker.ts"

[[durable_objects.bindings]]
name = "CART_DO"
class_name = "CartDurableObject"

[[durable_objects.bindings]]
name = "INVENTORY_DO"
class_name = "InventoryDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CartDurableObject", "InventoryDurableObject"]

[observability]
enabled = true
